### ISSUE TITLE
Добавить функцию attachHolds(Кол-во удержаний, функция)

### ISSUE THREAD

**Issue by Roman-Andr** [GyverLibs/EncButton#1]
Было бы неплохо добавить функцию на подобии attachHolds(Кол-во удержаний, функция), которая будет вызывать функцию которую её передадут (как attach и attachClicks) когда кнопку удержали определённое количество раз. Также можно добавить счётчик удерживаний на подобии счётчика кликов.

**Comment by XRay3D** [comment]
А если ни секрет зачем оно надо? Конкретно я не люблю длинные тягомотные интерфейсы, где что то надо держать и-или ждать, у моря погоды.

**Comment by GyverLibs** [comment]
Можно тогда attachSteps ещё сделать, и пусть весь мир подождёт)
