### ISSUE TITLE
Добавить поддержку энкодера

### ISSUE THREAD

**Issue by VSVLAD** [GyverLibs/EncButton#10]
У меня есть энкодер, но прокрутка у него срабатывает только каждый второй раз. Насколько я понял, EncButton перестал поддерживать несколько типов энкодеров.

![large_image-6fa5b36c-b822-4468-bed4-bdf3d3b4daad](https://user-images.githubusercontent.com/3996284/147879832-9a53138f-86b6-4310-ba04-68b19570226c.jpg)

В локальной библиотечке у себя в методе:
`void poolEnc(uint8_t state)`

заменяю
`if (state == 0x3 && _ecount != 0) {`

на
`if ((state == 0x3 || state == 0x0) && _ecount != 0) {`

то всё работает как требуется.
Можете ещё один дефайн сделать и поправить код, чтобы поддержку этого энкодера включить?

-- edited:
Прикрепил корректную картинку

**Comment by bar2104y** [comment]
Поддерживаю, вариант решения выше работает

**Comment by GyverLibs** [comment]
Замутил, спасибо за готовый кусок кода! =)
