### ISSUE TITLE
isActive

### ISSUE THREAD

**Issue by AdamKhagar** [GyverLibs/EncButton#13]
хотелось бы иметь метод `isActive` который возвращал `bool`.

`isActive()` возвращает `true` если с энкодером/кнопкой происходит какое либо действие, в противном случае - `false`. Такой метод помог бы вынести всю логику связанную с обработкой действий с энкодером/кнопкой в отдельную функцию

```
void loop() {
    enc.tick();
    if (enc.isActive()) {
         doSomething();
    }
    .....
}

void doSomething() {
    // Здесь вся логика связанная с обработкой действий с кнопкой
    .....
}

**Comment by GyverLibs** [comment]
https://github.com/GyverLibs/EncButton/blob/main/examples/optimisation/optimisation.ino

**Comment by AdamKhagar** [comment]
Спасибо, не заметил когда смотрел примеры
