### ISSUE TITLE
Почему два класса

### ISSUE THREAD

**Issue by XRay3D** [GyverLibs/EncButton#14]
В чём основное различие между EncButton и EncButton2?
Возможно я могу помочь свести в один файл.

**Comment by XRay3D** [comment]
В чём основное различие между EncButton и EncButton2?
Возможно я могу помочь свести в один файл.

**Comment by GyverLibs** [comment]
Первый класс хранит номера пинов в шаблоне, второй - в переменных класса

**Comment by XRay3D** [comment]
От этого большой выигрыш памяти скорости?
Могу попробовать написать обёртку для шаблонного варианта. Но не уверен что это можно сделать в с++11.

**Comment by GyverLibs** [comment]
Выигрыш во всём - в шаблоне. Вторая версия класса сделана для удобного задания массива кнопок/энкодеров

**Comment by XRay3D** [comment]
Ок тогда попробую завернуть EncButton.

**Comment by XRay3D** [comment]
Похоже что виртуальными кнопками придётся пожертвовать или вынести отдельный класс.

**Comment by GyverLibs** [comment]
да зачем, и так всё отлично организовано. Сейчас отдельный класс нужен только для массива физических кнопок

**Comment by XRay3D** [comment]
> да зачем, и так всё отлично организовано. Сейчас отдельный класс нужен только для массива физических кнопок

Есть возможность всё в один свести.

**Comment by XRay3D** [comment]
https://github.com/XRay3D/EncButton/tree/master
Борщенул с CRTP и выиграл от 50 до 102 байт по флешу.
Теперь всё в одном классе. 
Хотел ещё и недопустимые для выбранного типа проверки состояний вынести в ```ButtonImpl``` и ```EncoderImpl```

**Comment by GyverLibs** [comment]
Божечки! При всем желании не смогу разобраться, как оно работает)

**Comment by XRay3D** [comment]
> Божечки! При всем желании не смогу разобраться, как оно работает)

https://en.cppreference.com/w/cpp/language/partial_specialization
https://en.cppreference.com/w/cpp/language/crtp
https://en.cppreference.com/w/cpp/language/qualified_lookup
https://en.cppreference.com/w/cpp/language/adl

**Comment by XRay3D** [comment]
https://en.cppreference.com/w/cpp/language/crtp
Это как "класс из кубиков лего собирать".

**Comment by XRay3D** [comment]
Брать будете)) Дизайнил из-за обратной совместимости. Почти.

**Comment by XRay3D** [comment]
https://youtu.be/-QOaUNFGj6E?t=2968

**Comment by XRay3D** [comment]
> Божечки! При всем желании не смогу разобраться, как оно работает)

Годнота по теме подъехала.
https://www.youtube.com/watch?v=UrL5gdW2JOM
