### ISSUE TITLE
Ошибка в схеме  энкодера

### ISSUE THREAD

**Issue by schpuntik** [GyverLibs/EncButton#16]
https://github.com/GyverLibs/EncButton/blob/main/doc/enc.png
Здесь в схеме допущена ошибка . Сопротивления  R12 и R13  в енкодере находятся в другом месте.  Между   конденсатором и выходом энкодера как А  так и В    А пины  сразу выходят  с кондесаторов.
https://drive.google.com/file/d/1GKEJEZuG_lee2cvp-ihmwgnxtwhLmuWn/view?usp=sharing

**Comment by GyverLibs** [comment]
Согласен, сейчас поправлю. Некрасивый RC фильтр получился. Видимо я ориентировался на первую схему отсюда https://hackaday.com/2015/12/09/embed-with-elliot-debounce-your-noisy-buttons-part-i/
