### ISSUE TITLE
Работа энкодера.

### ISSUE THREAD

**Issue by schpuntik** [GyverLibs/EncButton#19]
У меня энкодер как   такой  же как здесь. https://github.com/GyverLibs/EncButton/issues/10   
Я прописал   дефайны вот так.
`#define EB_BETTER_ENC   // улучшенный алгоритм опроса энкодера. Добавит 16 байт SRAM при подключении библиотеки
#define EB_HALFSTEP_ENC // режим опроса полушагового энкодера (включи, если твой энкодер делает два тика за один)`
Но  энкодер  всё равно  работает без изменений  2 к 1.  Что я делаю не так?

**Comment by GyverLibs** [comment]
Перед подключением библиотеки?

**Comment by schpuntik** [comment]
ДА  Так  и есть.

**Comment by schpuntik** [comment]
Всё разобрался.  Снова  невнимательность новичка.
Я прописал  перед  декларацией энкодера  но не  библиотеки.
Теперь прописал   перед библиотекой и всё  заработало .
Спасибо на наводку.
