### ISSUE TITLE
Приоритет оптимизации.

### ISSUE THREAD

**Issue by XRay3D** [GyverLibs/EncButton#20]
Приоритетная цель оптимизации скорость исполнения или занимаемая память?

**Comment by GyverLibs** [comment]
И то и то, сбалансированно. В текущей версии можно вытащить из битовых полей три переменные, которые опрашиваются постоянно. Это срежет 0.5 мкс, но добавит +2 байта рамы, больше оптимизировать на мой взгляд нечего (мои полномочия на этом всё :)

**Comment by XRay3D** [comment]
Эмулятор - софтовое тестирование
[EncButtonTest.zip](https://github.com/GyverLibs/EncButton/files/8040216/EncButtonTest.zip)
е

**Comment by GyverLibs** [comment]
у нас тут новая версия! =)

**Comment by brightproject** [comment]
> у нас тут новая версия! =)

Это великолепные новости!

**Comment by GyverLibs** [comment]
открыл эту либу, хоспаде страшный сон индуса)
