### ISSUE TITLE
32767 on arduino nano 

### ISSUE THREAD

**Issue by zoldaten** [GyverLibs/EncButton#21]
Используется arduino nano и encoder e6b2-cwz1x.
Во время использования библиотеки с инкрементарным энкодером значения растут до 32767. Далее выводится 
-32768 и счетчик уменьшается, выводя отрицательные значения. Хотя направления энкодера не изменяется. Далее, после достижения -32768, счетчик снова становится положительным, однако значения продолжают уменьшаться. 
С чем это может быть связано и как это исправить ?

**Comment by AlexGyver** [comment]
библиотека хранит количество шагов энкодера в переменной типа int. Если нужно больше - можно в файле библиотеки сделать тип у этой переменной int32_t, будет +-2 147 483 648
