### ISSUE TITLE
Работа EncButton на матричной клавиатуре 

### ISSUE THREAD

**Issue by Maxim0x00k** [GyverLibs/EncButton#22]
Добрый день! Я заранее извиняюсь, если вопрос глупый, но я перед этим гуглил и искал и правда не нашел как внедрить двойной клик в матричную клавиатуру. В виртуальном режиме указано 

> Виртуальный режим позволяет получить все возможности библиотеки EncButton в ситуациях, когда кнопка не подключена напрямую к микроконтроллеру, либо для её опроса используется другая библиотека:
Аналоговая клавиатура (например через библиотеку [AnalogKey]
Матричная клавиатура (например через библиотеку [SimpleKeypad])"

Вопрос, как с помощью этой библиотеки сделать одну или несколько кнопок на матричной клавиатуре c двойным нажатием ?

**Comment by GyverLibs** [comment]
привет, передавать актуальное состояние кнопок в tick. Объект библиотеки EncButton должен быть настроен в виртуальный режим, как во встроенном примере virtual

**Comment by GyverLibs** [comment]
Ну, вообще абсолютно не так) добавлю примеры через часок

**Comment by Maxim0x00k** [comment]
@GyverLibs Я буду вам дико благодарен!

**Comment by GyverLibs** [comment]
закинул. Нужно обновить библиотеку, я сделал чтобы в виртуальном режиме уровень кнопки сразу был высокий, для более логичной работы

**Comment by Maxim0x00k** [comment]
@GyverLibs Громадное вам спасибо!!!
