### ISSUE TITLE
Turn events fire only after two "ticks"

### ISSUE THREAD

**Issue by Mark-81** [GyverLibs/EncButton#24]
It's hard for me to understand how the library works and to search here because you don't write in English.
Anyway, using the examples provided I see it prints out a turn event only after two "ticks" of my encoder in either direction.

I'm using a common ALPS EC12D1564402.

Is there any setting to change in order to see every "tick"?

**Comment by GyverLibs** [comment]
Hi, you have single-pulse encoder. Library can works with them in `EB_BETTER_ENC` mode and `EB_HALFSTEP_ENC`
