### ISSUE TITLE
Не работает "Полушаговый" энкодер

### ISSUE THREAD

**Issue by Denis20221** [GyverLibs/EncButton#26]
Стоит какойто полушаговый энкодер, что бы произошел тик, надо два щелчка прокрутить. Это при стандартных настройках библиотеки.

Запустил голый пример из библиотеки под названием optimisation, и вставил #define EB_HALFSTEP_ENC, а после полез смотреть в serial. Там при прокрутке энкодер чудит. При прокрутке сначала вправа, показывает turn right, при повторной прокрутке вправо "turn left turn right". аналогично при прокрутке влево. Кнопка SW вообще реагировать перестала.

**Comment by GyverLibs** [comment]
Алгоритм `EB_HALFSTEP_ENC` не очень хорошо работает из за особенности таких энкодеров, у меня часть энкодеров работает  идеально, часть - иногда с ошибкой направления шага. Рекомендую использовать совместно с `EB_BETTER_ENC` - чуть тяжелее но отрабатывает чётко любые энкодеры.  
Но в реализации действительно был небольшой косяк, спасибо! Я релизнул v1.22, теперь энкодер работает более правильно и указанный пример реагирует на кнопку

**Comment by Denis20221** [comment]
Благодарю! Обновил библиотеку и задействовал EB_HALFSTEP_ENC+EB_BETTER_ENC.
Все заработало.
