### ISSUE TITLE
Подключение кнопки

### ISSUE THREAD

**Issue by Masturbek** [GyverLibs/EncButton#28]
Подключил кнопку следующим образом:
![image](https://user-images.githubusercontent.com/61079028/164090570-0d7f1e4b-27a2-4f0c-a156-b617c9e75fd7.png)
при нажатии на кнопку происходит просадка напряжения питания, как это можно пофиксить?

**Comment by GyverLibs** [comment]
Питать от источника, который не боится тока  0.1 мА

**Comment by Masturbek** [comment]
Я попробовал запитать от повербанка, он может отдавать минимум 1А тока, но мерцание при нажатии есть все равно, это уже никак не исправить?

**Comment by Masturbek** [comment]
Хорошо, спасибо за ответ!
