### ISSUE TITLE
Использование RX/TX (GPIO3/GPIO3) в качестве А и В в pinmode, A, B, KEY

### ISSUE THREAD

**Issue by brightproject** [GyverLibs/EncButton#29]
Подскажите, использую ESP8266 в схеме управления котлом.
Почти все стандартные выхода D0...D7 на вход и выход заняты.
_Остались GPIO9 и GPIO10, а также RX/TX (GPIO3/GPIO3)._
Эта библиотека не может опрашивать данные ноги на вход?
Пробовал и через:

> pinMode(1, FUNCTION_3);
> pinMode(1, INPUT);

Часть кода такая:

> #include <SPI.h>
> #include <EncButton2.h>
> EncButton2<EB_ENCBTN> enc(INPUT, 1, 3, D7);  // энкодер с кнопкой (A, B, KEY)
> void setup() {
>   pinMode(1, INPUT);
>   pinMode(3, INPUT);
>   Serial.begin(115200);
> }

Ничего не происходит...
Не хотелось бы использовать мультиплексоры - все таки надо, чтобы устройство не потребляло много электричества и было отчасти "автономным".

**Comment by GyverLibs** [comment]
Библиотека работает с любыми GPIO пинами, опрашивая их как digitalRead(). Дублировать пинмоды не нужно, они настраиваются в библиотеке.

По поводу системных пинов esp8266 смотрите документацию и схемотехнику конкретной платы, там много особенностей и ограничений

**Comment by brightproject** [comment]
Благодарю за ответ, возможно, что у меня при использовании например пина RX - не выполняется его опрос из-за того, что он(GPIO9) не "подтянут" к земле или 3.3 вольтам?

**Comment by GyverLibs** [comment]
Кнопку в принципе невозможно опросить, если пин болтается в воздухе, он обязательно должен быть подтянут противоположно подключению кнопки. Именно поэтому input pullup во всех примерах сделан

**Comment by brightproject** [comment]
> Кнопку в принципе невозможно опросить, если пин болтается в воздухе

А энкодер?

**Comment by GyverLibs** [comment]
А энкодер это физически просто две кнопки. Если используется голый энкодер - нужно подтягивать пины. Если используется китайский модуль - там уже всё подтянуто к vcc

**Comment by brightproject** [comment]
> Если используется китайский модуль - там уже всё подтянуто к vcc
Использую "китайский" круглый, где подтянуто.
Но все равно не работает RX на вход...

**Comment by GyverLibs** [comment]
Также нужно помнить, что прижатый к GND пин TX не даст esp запуститься, с энкодером - модулем такое возможно если позиция энкодера "не защелкнута"

**Comment by brightproject** [comment]
> прижатый к GND пин TX не даст esp запуститься

ESP запускается, но когда в TX or RX находится какой либо контакт от энкодера, то прошивка не начинается.

**Comment by GyverLibs** [comment]
Эм, сериал не будет работать, если на его ноги повесить энкодер...

**Comment by GyverLibs** [comment]
Если хочется пинов сэкономить - нужно делать энкодер отключаемым на момент прошивки, а сериал - не запускать

**Comment by brightproject** [comment]
> сериал - не запускать

Хочется еще и отладку делать)

**Comment by GyverLibs** [comment]
Ну, значит есп32 брать

**Comment by brightproject** [comment]
> Ну, значит есп32 брать

У нее при использовании всех пинов - это не мешает отладке?

**Comment by GyverLibs** [comment]
У неё просто пинов раза эдак в 4 больше, хватит на любой каприз и ещё останется

**Comment by brightproject** [comment]
Спасибо за подсказки.
Доброй ночи!

**Comment by GyverLibs** [comment]
Удачи)

**Comment by brightproject** [comment]
Подскажите, можно использовать сдвиговый регистр или мультиплексор для подключения энкодера?

**Comment by GyverLibs** [comment]
можно, но это будет работать плохо или вообще не будет
