### ISSUE TITLE
Умеет-ли isPress() обрабатывать быстрые клики?

### ISSUE THREAD

**Issue by khusamov** [GyverLibs/EncButton#3]
Здравствуйте!
Спасибо за библиотеку и канал!
Вопрос:

Можно ли при помощи isPress() обрабатывать клики, между которыми очень маленький промежуток?

Я когда кликаю пример 2-3 раза в сек. то все нормально, но если кликать быстрее, то некоторые клики пропускаются. Как это исправить?

**Comment by GyverLibs** [comment]
Уменьшать debounce (см. Документацию, дефайн eb deb) пока не будет нужная чувствительность. Но не до появления ложных кликов, скорее всего в районе 50мс надо сделать

**Comment by khusamov** [comment]
Спасибо! Попробовал! Наконец-то пули начали бодро вылетать из пушки. А то приходилось ждать, когда можно было следующую пулю выпустить.
