### ISSUE TITLE
ArduinoOTA не работает при вызове метода enc.tick()

### ISSUE THREAD

**Issue by borodihin** [GyverLibs/EncButton#33]
Проект на esp32. Функция loop () выглядит примерно следующим образом:
```
void loop () {
  ArduinoOTA.handle();
  enc.tick();
  getSensors();
}
```
В случае вызова метода enc.tick(), при работе стандартных процедур ArduinoOTA код в loop() продолжает выполняться, тем самым прерывая обновление.
Энкодер подключен без использования прерываний.

**Comment by GyverLibs** [comment]
> код в loop() продолжает выполняться

а не должен?

**Comment by borodihin** [comment]
Я так понимаю, что пока грузится обновление по воздуху - не должен. Во всяком случае, если tick() не вызываю - не выполняется.

**Comment by GyverLibs** [comment]
К сожалению ничем не могу помочь, у меня ArduinoOTA отказывается работать на esp32. Что можно попробовать:
- Обновить ядро esp32
- Обновить ArduinoOTA
- Заменить `enc.tick();` на три штуки `digitalRead()` - по сути кроме чтения пина в тике ничего не происходит
- Включить отладку в ядре esp32, посмотреть что пишет
- Включить встроенную в ArduinoOTA обработку статусов как в примере ArduinoOTA (onStart, onEnd...)

**Comment by GyverLibs** [comment]
Мне удалось завести ArduinoOTA, всё работает без проблем. Возможно стоит обновить ядро esp32, оно до сих пор в активной разработке и довольно криво работает.
![image](https://user-images.githubusercontent.com/84599917/200234063-19355b6e-cde3-4376-8e1e-1a8cb19d4999.png)

**Comment by borodihin** [comment]
getSensors() у меня выводит на дисплей значения сенсоров, в ArduinoOTA обработка статусов включена и на тот же дисплей выводится прогресс обновления. В другом месте программы по прерыванию таймера на дисплей выводится текущее время, поэтому прерывания по таймеру приходится выключать при начале обновления.
Если вызываю enc.tick() значения сенсоров отображаются на дисплее "поверх" статуса обновления. Если закомментировать - всё нормально.
В любом случае, спасибо за помощь!

**Comment by GyverLibs** [comment]
Значит надо ковырять дальше, начать с этого
- Обновить ядро esp32
- Обновить ArduinoOTA
- Заменить enc.tick(); на три штуки digitalRead() - по сути кроме чтения пина в тике ничего не происходит
- Включить отладку в ядре esp32, посмотреть что пишет
- Посмотреть, какой статус ошибки появляется у ArduinoOTA

**Comment by borodihin** [comment]
Чудеса:
если enc.tick();  вызываю в конце цикла loop() всё работает.
`void loop () {
  ArduinoOTA.handle();
  getSensors();
  enc.tick();
}`
