### ISSUE TITLE
Не помещается в ATtiny13

### ISSUE THREAD

**Issue by MrOzean** [GyverLibs/EncButton#34]
Версия библиотеки: 2.0
Какой используется МК: ATtiny13A + [MicroCore](https://github.com/MCUdude/MicroCore)

Библиотека настроенная для полноценного энкодера с кнопкой [фото](https://github.com/GyverLibs/EncButton/raw/main/doc/encAli.png) не помещается во флеш память  ATtiny13 

```cpp
#include <EncButton.h>
#include <stdbool.h>

#define ENCODER_KEY_PIN 2
#define ENCODER_ROT_RIGHT_PIN 3
#define ENCODER_ROT_LEFT_PIN 4
#define PWM_PIN 0

EncButton<EB_TICK, ENCODER_ROT_RIGHT_PIN, ENCODER_ROT_LEFT_PIN, ENCODER_KEY_PIN> enc;  

bool onOff = TRUE;

void setup() {
}

void loop() {
  if (enc.tick()) {
    if (enc.click())
      onOff = !onOff;
  }
}
```
Этот код занимает 1142 байт(111%) флеша.
Это баг библиотеки, выбранного ядра, или она в принципе не поддерживает камни меньше ATtiny85?

**Comment by GyverLibs** [comment]
Видимо для всех возможностей библиотеки килобайта флэша будет маловато 😂 будет время - сделаю микро версию с более дешёвыми алгоритмами

**Comment by MrOzean** [comment]
Эх, пошёл искать тогда библиотеку поменьше. Ты убери из описания ATtiny13, чтобы людей не смущать 😅

**Comment by GyverLibs** [comment]
ну так то для тини13 заявлена скорость чтения пина, а не память) обработка кнопки скорее всего влезет

**Comment by MrOzean** [comment]
Одной кнопкой сыт не будешь 😅

**Comment by GyverLibs** [comment]
в принципе сами алгоритмы обработки занимают 600 байт, есть потенциал для тини-либы

**Comment by GyverLibs** [comment]
новая версия вмещается =)
