### ISSUE TITLE
Нет реакции на поворот энкодера на LGT8F328p

### ISSUE THREAD

**Issue by dazre** [GyverLibs/EncButton#35]
Энкодер синий :)

клик, холд отрабатывает в обоих режимах: тик и коллбэк. поворот не фиксируется ни в одном из режимов. проявляется на примерах из библиотеки.

**Comment by GyverLibs** [comment]
Использовать пины в режиме input. Pullup нельзя, он у lgt328 слишком сильный и это создаёт делитель напряжения gnd не доходит

**Comment by dazre** [comment]
Спасибо! Заработало
