### ISSUE TITLE
Todo?

### ISSUE THREAD

**Issue by GyverLibs** [GyverLibs/EncButton#43]
- не сбрасывать таймер в pressisr если уже busy. Или уже deb?

**Comment by brightproject** [comment]
Если можно, то в класс кнопки `class Button : public VirtButton {}`
добавить чтение в секции setup с дебонсом, что то наподобие
```
    bool read_debounce() {
        static uint32_t ms;
        static uint8_t pinVal;

        ms     = millis();
        pinVal = digitalRead(pin);
        if (_invert != 0) pinVal = !pinVal;
        if (ms - _lastChange < _dbTime) {
            _lastTime = _time;
            _time     = ms;
            _changed  = 0;
            return _state;
            // return EBread(pin) ^ read_bf(EB_INV);
        } else {
            _lastTime  = _time;
            _time      = ms;
            _lastState = _state;
            _state     = pinVal;
            if (_state != _lastState) {
                _lastChange = ms;
                _changed    = 1;
                if (_state) {
                    _pressTime = _time;
                }
            } else {
                _changed = 0;
            }
            return _state;
            // return EBread(pin) ^ read_bf(EB_INV);
        }
    }
```
Пробовал поэкспериментировать - но как то криво работало у меня это.
Оставил как было
```
    bool read() {
        return EBread(pin) ^ read_bf(EB_INV);
    }
```

**Comment by GyverLibs** [comment]
Нет, это ерунда какая то

**Comment by GyverLibs** [comment]
Если по каким то причинам нужно именно остаться в сетап, без примера с флагом как я писал ранее, то можно воспользоваться состоянием busy и погрузиться в цикл
```cpp
void setup() {
  do {
    btn.tick();
    if (btn.click()) foo();
  } while (btn.busy());
}
```

**Comment by GyverLibs** [comment]
Есть нужно две и более кнопок затащить в обработку при старте - соответственно 
```cpp
while (b1.busy() || b2.busy() || b3.busy());
```

**Comment by brightproject** [comment]
> Нет, это ерунда какая то. Опять же чтобы подобный код работал - его нужно вызывать циклично, в сетап это не будет работать

Вы как адепт ардуино, все же создали многие библиотеки "универсальными", работающими и с другими МК.
Сейчас популярный чип это esp32-s3 и teensy 4.1
Используя вашу библиотеку, еще версии 2, столкнулся с тем, что на esp32 она работала не совсем так как надо, особенно с энкодерами.
Стал разбираться, и оказалось, разработчики esp32 аппаратно сделали поддержку энкодера, назвали ее PCINT - то есть прерывания аппаратные.
Вы не думали реализовать поддержку PCINT в своей библиотеке?

**Comment by GyverLibs** [comment]
> сделали поддержку энкодера, назвали ее PCINT

PCINT это обычные прерывания с пина, к энкодеру это никакого отношения не имеет... Библиотека изначально сделана универсальной для работы с прерываниями на любых платформах, в прерывании нужно вызвать специальный тикер. К слову PCINT есть и у МК AVR

**Comment by GyverLibs** [comment]
Это библиотека энкодера от esp32, там же написано `rotary_encoder.h`. Encbutton не будет совмещаться с другими фреймворками и от них зависеть, это не имеет смысла. Encbutton замечательно интегрируется с любой платформой, потому что функция опроса помещается в обработчик прерывания
