### ISSUE TITLE
the 'eb.clear()' does not really set the encoder counter to 0

### ISSUE THREAD

**Issue by TS32** [GyverLibs/EncButton#45]
Thanks for your great work and it's a useful and elegant lib which saved me quite a lot of time.
With the EncButton, I found there is no way to clear the counter. eg, I turn to a position and need to tell the program the current position is '0', so I can double click the button to trigger that, however the 'eb.clear()' does not really set the encoder counter to 0.  could you help?

**Comment by GyverLibs** [comment]
Hi, `counter` is a public class variable, you can do whatever you want with it:
```cpp
eb.counter = 0;
eb.counter += 100;
Serial.println(eb.counter)
```
