### ISSUE TITLE
Как задать #define EB_HOLD для разных кнопок разные значения?

### ISSUE THREAD

**Issue by khusamov** [GyverLibs/EncButton#5]
Добрый день!

Параметр #define EB_HOLD влияет на все кнопки. А как задать этот параметр для кнопок отдельно?

Например для вращения пушки нужно значение нуль, а вот для кнопки выстрела очередями нужна небольшая задержка (чтобы была возможность стрелять отдельными пулями и очередями).

**Comment by GyverLibs** [comment]
Аааа к сожалению никак, библиотека создавалась как максимально оптимальная для мк без байта лишнего кода, всё на константах. Нужный функционал можно добавить у себя локально, там пару строчек дописать

**Comment by khusamov** [comment]
То есть не для игр библиотека. Понимаю.

А локально это как? Скопировать к себе и править под себя? Или можно как-то без копирования сделать?

**Comment by GyverLibs** [comment]
Ну, скачать себе библу и добавить переменную вместо константы

**Comment by GyverLibs** [comment]
Сделал индивидуальную настройку удержания в 1.8
