### ISSUE TITLE
Совместимость с ESP8266 (Wemos D1 Mini) 

### ISSUE THREAD

**Issue by A2020GK** [GyverLibs/EncButton#51]
Здравствуйте! Суть проблемы: библиотека плохо работает на ESP8266, контроллер перезагружается при повороте/нажатии на кнопку энкодера. С Arduino Nano этот же энкодер работает стабильно. Может проблема в самой плате?

**Comment by GyverLibs** [comment]
Примеры из библиотеки работают корректно? Какие используются пины?

**Comment by A2020GK** [comment]
Пример demo:
Работает только кнопка. Пробовал пины: D5, D6, D7 и D3, D4, D7.

**Comment by GyverLibs** [comment]
Проверил, работает корректно

**Comment by A2020GK** [comment]
Хорошо, спасибо. Возможно действительно проблема в плате.
