### ISSUE TITLE
Передать аргументы в событие.

### ISSUE THREAD

**Issue by jackfrombb** [GyverLibs/EncButton#52]
Здравствуйте.
Во первых, спасибо за работу)

Теперь к делу. При реализации энкодера в классе, приходится делать метод события статическим, что лишает достпа к локальным переменным класса. Если будет  такая возможность, то добавьте передачу аргументов в событие.

Сам я не хотел бы пул реквестить в библиотеку, без нормального понимания внутренней структуры и достаточной компетенции в плюсах.

**Comment by GyverLibs** [comment]
Привет, каких аргументов? Не очень понятна ситуация, нужно подробности

**Comment by jackfrombb** [comment]
> Привет, каких аргументов? Не очень понятна ситуация, нужно подробности

Вот пример. 
Только сразу договоримся, что "метод" = "функция"  и наоборот, точно не знаю как в плюсах принято) 
Предположим, надо определить реализацию контроля от виртуального класса.
Присоеденить не статический метод класса мы не сможем, из за несовпадения типов.
![photo_2024-01-10_14-37-27](https://github.com/GyverLibs/EncButton/assets/59813353/de00ce2b-ed7c-4bf2-9c05-863f4fcb2ab8)

Но, если мы сделаем метод статическим, то поля класса становятся недоступны, что логично
![photo_2024-01-10_14-29-40](https://github.com/GyverLibs/EncButton/assets/59813353/b07d1794-9491-481f-9341-3f4e57a4a00b)

Я вижу такое, возможное, решение:

Делаем событие с аргументами, например, в стиле WindowsForms)
![photo_1](https://github.com/GyverLibs/EncButton/assets/59813353/cb5c8c89-b22d-4fae-804d-542cb9e6059b)

Чуть изменяем привязку события
![photo_2](https://github.com/GyverLibs/EncButton/assets/59813353/e5b39199-3a9d-4d07-a187-8ae6209f8910)

И вызов
![photo_3](https://github.com/GyverLibs/EncButton/assets/59813353/d0f57b9c-3895-409d-a129-c0e3fd2adab1)

Тогда в классе можно сделать так:
![photo_4](https://github.com/GyverLibs/EncButton/assets/59813353/c53430e9-bfaf-49dc-83d3-e7ad3a9de097)

**Comment by GyverLibs** [comment]
а зачем вообще использовать attach в классе, если всё равно вызывается тикер и action можно опросить там же?..

**Comment by GyverLibs** [comment]
также можно использовать лямбда-функцию

**Comment by jackfrombb** [comment]
> а зачем вообще использовать attach в классе, если всё равно вызывается тикер и action можно опросить там же?..

В этом случае, при некоторых обстоятельствах, очень глючит. В частности, когда прерывания забирают много веремени у loop.

**Comment by GyverLibs** [comment]
> очень глючит

не может такого быть)) Приаттаченный хэндлер вызывается из тикера
```cpp
    bool tick(bool s) {
        clear();
        s = pollBtn(s);
#ifndef EB_NO_CALLBACK
        if (cb && s) cb();
#endif
        return s;
    }
```

то есть `if (enc->tick()) myHandler();` это абсолютно тот же самый код получится

**Comment by jackfrombb** [comment]
> > очень глючит
> 
> не может такого быть)) Приаттаченный хэндлер вызывается из тикера
> 
> ```c++
>     bool tick(bool s) {
>         clear();
>         s = pollBtn(s);
> #ifndef EB_NO_CALLBACK
>         if (cb && s) cb();
> #endif
>         return s;
>     }
> ```
> 
> то есть `if (enc->tick()) myHandler();` это абсолютно тот же самый код получится

Ок. Значит тогда глючило из за того что не вызывал тик в прерывании) Значит, вполне годное решение, спасибо ещё раз)
```
/// @brief Прерывание для обработки пропущенных считываний энкодера
/// @param args = NULL
/// @return nothing
bool IRAM_ATTR encTick(void *args)
{
    enc.tickISR();
    return false;
}
```
