### ISSUE TITLE
Внутрення подтяжка пинов INPUT_PULLUP

### ISSUE THREAD

**Issue by tiffass** [GyverLibs/EncButton#55]
Не могу понять работает ли эта библиотека с внутренней подтяжкой пинов?
В примере demo написано
EncButton eb(2, 3, 4, INPUT); // + режим пинов энкодера
Меняю INPUT на INPUT_PULLUP  и ничего не работает. Точнее в одном из положений энкодера в мониторе порта видно что постоянно идет информация о вращении энкодера. Тип энкодера **eb.setEncType(EB_STEP2);**
Пробовал разные варианты 
EncButton eb(2, 3, 4, INPUT_PULLUP);
EncButton eb(2, 3, 4, INPUT_PULLUP,INPUT_PULLUP);
EncButton eb(2, 3, 4, INPUT_PULLUP,INPUT_PULLUP,INPUT_PULLUP);
и даже pinMode(2, INPUT_PULLUP); pinMode(3, INPUT_PULLUP);
результат одинаковый.
С внешней подтяжкой все нормально.

**Comment by GyverLibs** [comment]
Всё работает отлично, внимательнее к схеме своего энкодера

**Comment by tiffass** [comment]
Какая может быть схема? 3 проводка?

**Comment by GyverLibs** [comment]
Мне то откуда знать? Голый это энкодер или модуль, если модуль то какой конкретно, и так далее

**Comment by tiffass** [comment]
Модуль KY-040
![KY-04-Rotary-Encoder-Pinout](https://github.com/GyverLibs/EncButton/assets/138359920/b81cae96-555e-4eb7-8518-1cab03b6edf7)

но резисторы подтяжки с платы выпаяны, т.к. в дальнейшем планирую использовать голый энкодер. CLK подключен к пину 2, DT - 3. Кнопка не подключена т.к. не нужна. GND соответственно к  GND ардуины. 
В мониторе такая картина

![mon](https://github.com/GyverLibs/EncButton/assets/138359920/9468499c-7d1e-4ff3-9a56-1665a8d9c169)

С запаянными резисторами и подключенным "+" - все нормально

**Comment by GyverLibs** [comment]
Можно прописать вручную пинмод input pullup на пины энкодера в setup(). Также возможно похожая проблема была в одной из прошлых версий gyverio, так что первым делом нужно обновить и енкбатн и gyverio до актуальных версий. Если не заработает - через несколько дней буду у компьютера, возьму такой же модуль, проверю. Какой микроконтроллер?

**Comment by tiffass** [comment]
> Можно прописать вручную пинмод input pullup

Пробовал - не помогает



> обновить и енкбатн и gyverio до актуальных версий

С этого и начал


> Какой микроконтроллер?

Arduino uno - mega328

**Comment by tiffass** [comment]
Хм ... полтергейст какой-то, попробовал еще раз прописать pinmodе input_pullup - заработало. А с EncButton eb(2, 3, 4, INPUT_PULLUP) так и не хочет

**Comment by GyverLibs** [comment]
Запряг человека протестировать, он перегрел энкодер когда выпаивал резики) пока вопрос открытый

**Comment by tiffass** [comment]
> а если добавить

Так работает, даже без bool EB_read(uint8_t pin).


> перегрел энкодер когда выпаивал

Газовой горелкой что-ли выпаивал? :)

**Comment by GyverLibs** [comment]
Феном.. 

видимо дело в gyverio режиме пина, буду разбираться

**Comment by GyverLibs** [comment]
всё пофиксил, спасибо за репорт

**Comment by tiffass** [comment]
> пофиксил

Да, теперь работает
