### ISSUE TITLE
Иногда нет обработки вращения энкодера

### ISSUE THREAD

**Issue by voshodvoshod** [GyverLibs/EncButton#57]
Доброго дня.
Arduino IDE 1.8.19
ESP-Wroom-32
ядро 2.0.11
EncButton 3.5.10 или 3.5.0 
 Энкодер подключён  GPI36(SP)-DT, GPI39(SN)-CLK, обработка в прерывании.
Примеры работают.
Проблемный фрагмент:
 if ( menu2 == true){
       if (eb.right() and setday < 31){                                // Если поворот по ЧС  и число меньше 31
       setday ++;                                                      // увеличим число  на 1  
       printday();                                                     // Выводим число                                         
       }
       if (eb.left() and setday > 1){                                  // Если поворот против ЧС и число больше 1
       setday --;                                                      // уменьшим число  на 1
       printday();                                                     // Выводим число
       }
     }
Должно бы работать так : читаем дату из Ds3231, присваиваем переменной setday текущее значение числа, поворотом энкодера изменяем её значение и выводим на экран. В сторону уменьшения работает как и должно. Увеличение не происходит,а выводится считанное из часов значение.
В скетче есть ещё аналогичный фрагмент выбора пункта меню, так там всё работает в обе стороны:
if (menu == true) {                                       //Если меню активно:
    if (eb.right() and ypointer != 3) {                    // Если поворот по ЧС и указатель не на 3 строке
         nopointer();                                      // Убираем курсор на предыдущей строке
         ypointer ++;                                      // Увеличим указатель на 1
         pointer();                                        // Рисуем курсор на указанном пункте
    }
    if (eb.left()and ypointer != 0) {                      // Если поворот против ЧС и указатель не на 1 строке
         nopointer();                                      // Убираем курсор на предыдущей строке
         ypointer --;                                      // Уменьшим указатель на 1
         pointer();                                        // Рисуем курсор на указанном пункте
   }
//......... / / здесь ещё строки
}
Почему так?
Вероятно, библиотека тут не причём, а причина в моём коде. Опыта немного.
Пытаюсь разобраться, а для этого нужно точно знать, что дело не в библиотеке.
Спасибо.

**Comment by GyverLibs** [comment]
Брать и отлаживать, выводить в serial что нибудь чтобы понимать заходит ли программа в ожидаемые условия и меняет ли переменные
