### ISSUE TITLE
Не подклюается библиотека EncButton

### ISSUE THREAD

**Issue by Swyatoslav2007** [GyverLibs/EncButton#60]
Возникает ошибка 
In file included from C:\Users\���������\Documents\Arduino\libraries\EncButton\src/core/VirtButton.h:5:0,
                 from C:\Users\���������\Documents\Arduino\libraries\EncButton\src/EncButton.h:4,
                 from C:\Users\Святослав\AppData\Local\Temp\.arduinoIDE-unsaved2024625-17272-1k0iiyb.y5f4\sketch_jul25a\sketch_jul25a.ino:2:
C:\Users\���������\Documents\Arduino\libraries\EncButton\src/core/io.h:3:10: fatal error: GyverIO.h: No such file or directory
 #include <GyverIO.h>
          ^~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: exit status 1

**Comment by GyverLibs** [comment]
Читаем ридми и ставим зависимости, либо ставим через менеджер библиотек
