### ISSUE TITLE
Энкодер type2

### ISSUE THREAD

**Issue by fergq** [GyverLibs/EncButton#62]
Извиняюсь сразу за возможно тупой вопрос, но в голову уже мысли не приходят, а многое вообще не понимаю..

Как указать что у меня энкодер второго типа чтобы он стал работать правильно? (https://alexgyver.ru/encoder/?ysclid=m30krqqfh8518972050 - " setType(type); // тип энкодера TYPE1 одношаговый, TYPE2 двухшаговый. Если ваш энкодер работает странно, смените тип ")

Ещё раз извинюсь если вопрос туповат

**Comment by GyverLibs** [comment]
Как в ридми/примерах

**Comment by fergq** [comment]
всё перепробовал - серовно не корректно работает (

.left вообще никак не хочет выдавать

**Comment by GyverLibs** [comment]
https://github.com/GyverLibs/EncButton?tab=readme-ov-file#%D1%82%D0%B8%D0%BF-%D1%8D%D0%BD%D0%BA%D0%BE%D0%B4%D0%B5%D1%80%D0%B0

**Comment by fergq** [comment]
а, упс.. я пины попутал, спасибо большое
