### ISSUE TITLE
Не работает `Button.releaseHold()`

### ISSUE THREAD

**Issue by rokokol** [GyverLibs/EncButton#63]
У меня вот такой вот код:
```
Button left_button(BUTTON_L);
if (left_button.hold()) {
  Serial.println("left hold");
} else if (left_button.step(1)) {
  Serial.println("left step 1");
} else if (left_button.click(1)) {
  Serial.println("left click");
} else if (left_button.releaseHold()) {
  Serial.println("left release hold");
}
```
При зажатии выводится `left hold`, но при отпускании `left release hold` не выводится

**Comment by GyverLibs** [comment]
releaseHold это отпускание между началом удержания и режимом step

**Comment by rokokol** [comment]
Понял, спасибо. Было бы здорово, если бы в будущем появилась функция для обработки отпускания после долгого удержания

**Comment by GyverLibs** [comment]
Всё есть с самого релиза библиотеки, достаточно почитать документацию
