### ISSUE TITLE
EncButtonT использует deprecated метод  bool VirtButton::timeoutState(uint16_t)

### ISSUE THREAD

**Issue by Shersula** [GyverLibs/EncButton#67]
Использую EncButtonT для обработки right()/left()/rightH()/leftH()/click()
Во время компиляции выдает предупреждение о использовании устаревшего метода timeoutState из VirtButton.h

Создание экземпляра энкодера
![image](https://github.com/user-attachments/assets/daf58c41-22ad-4786-b6c2-5e302b289122)

Использование энкодера
![image](https://github.com/user-attachments/assets/14ae77dd-b74b-4a00-8764-97b34ccd5867)

Дефайны настроек описаны в platformio.ini
![image](https://github.com/user-attachments/assets/5eb64a87-1189-4da6-9214-e1779ca407f9)

Вывод во время компиляции:
![image](https://github.com/user-attachments/assets/49c73b69-2d18-47e5-8a5f-208ba87ddba7)

**Comment by GyverLibs** [comment]
видимо придётся просто убрать deprecated

**Comment by Shersula** [comment]
@GyverLibs Это и правда был баг компилятора, не знаю что поменялось, но сегодня без обновления библиотеки и изменения кода, варнинг исчез.
Видимо это сюрпризы со стороны PlatformIO

**Comment by GyverLibs** [comment]
Ну я убрал deprecated. По сути что было - внутри deprecated метода вызывался deprecated метод. Сам верхний метод в библиотеке нигде не вызывается, поэтому с чего компилятор на него триггерится непонятно
